// <auto-generated />
namespace BK_API_QUIZ_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class phuong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phuong));
        
        string IMigrationMetadata.Id
        {
            get { return "202009231346476_phuong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
